version: '3'
services:
  webdocs:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./site
        target: /usr/share/nginx/html
        read_only: false
    ports: 
      - 80:80/tcp