---
site_name: EXPECA Testbed Documentation
theme:
  name: material
  font:
    text: Ubuntu
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
  repo_url: https://github.com/KTH-EXPECA/docs
  copyright: Copyright &copy; 2016 - 2020 EXPECA Project Group at KTH Royal Institute of Technology
...