---
site_name: EXPECA Testbed Documentation
theme: 
  palette:
    scheme: default
    primary: indigo
    accent: amber
  logo: assets/kth_logo.png
  name: material
  font:
    text: Ubuntu
    code: JetBrains Mono
  icon:
    # logo: fontawesome/solid/server
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
repo_url: https://github.com/KTH-EXPECA/docs
repo_name: KTH-EXPECA/docs
copyright: Copyright &copy; 2020 - EXPECA Project Group at KTH Royal Institute of Technology
markdown_extensions:
  - pymdownx.highlight:
      linenums: yes
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
plugins:
  - awesome-pages
...